# Generated by Django 3.1.6 on 2021-02-18 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapper.group')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('event_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('interest_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapper.group')),
            ],
        ),
    ]
