# Generated by Django 3.1.6 on 2021-02-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_class_id',
            new_name='group_class',
        ),
    ]
