# Generated by Django 3.1.6 on 2021-02-18 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_auto_20210218_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapper.group'),
        ),
    ]
