# Generated by Django 3.1.6 on 2021-02-18 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_auto_20210218_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='non_interesting_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.CreateModel(
            name='interesting_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.event')),
            ],
        ),
    ]
